In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!pip install torch torchvision

In [3]:
import torch
import torchvision
import numpy as np

In [4]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5)
print (x)
print(x.type())

tensor([[[-1.9074e+00,  3.9419e-01,  9.9539e-01,  7.0182e-01,  6.4419e-01],
         [-2.6407e-01,  1.2535e+00,  1.6054e+00,  1.9917e-01,  1.8942e+00],
         [ 1.1060e+00, -1.3121e-01,  9.6282e-01, -1.2782e-02,  1.9960e+00],
         [ 9.5395e-01, -4.3152e-01, -5.1356e-01,  6.3469e-01,  4.7221e-01]],

        [[-6.0254e-01,  8.2708e-01, -2.3133e-03,  6.3096e-01,  2.2643e-01],
         [-1.5486e+00, -2.4911e+00,  1.3089e-01,  1.2135e+00, -2.6380e+00],
         [-6.0109e-01, -1.4022e+00, -1.1291e+00, -3.9274e-01,  8.9849e-02],
         [-9.0763e-01,  4.6464e-01, -5.9253e-01,  8.2619e-01,  2.4516e+00]],

        [[ 1.0161e+00, -1.0637e-01,  1.4930e+00,  8.0728e-01,  2.4033e-01],
         [-5.3844e-01,  1.6548e+00,  8.3420e-03,  6.2744e-01, -1.0980e+00],
         [ 4.2749e-01, -6.8016e-01, -2.9928e-01,  1.0795e+00,  2.6041e-01],
         [ 6.7689e-01,  1.3593e-01, -7.1369e-02,  2.7712e+00, -1.3757e-01]]])
torch.FloatTensor


In [5]:
# 2. Выведите его форму (shape)

print(x.shape)

torch.Size([3, 4, 5])


In [6]:
# 3. Приведите его к форме 6 X 10

b = x.reshape(6,10)
print (b)
print(b.shape)

tensor([[-1.9074e+00,  3.9419e-01,  9.9539e-01,  7.0182e-01,  6.4419e-01,
         -2.6407e-01,  1.2535e+00,  1.6054e+00,  1.9917e-01,  1.8942e+00],
        [ 1.1060e+00, -1.3121e-01,  9.6282e-01, -1.2782e-02,  1.9960e+00,
          9.5395e-01, -4.3152e-01, -5.1356e-01,  6.3469e-01,  4.7221e-01],
        [-6.0254e-01,  8.2708e-01, -2.3133e-03,  6.3096e-01,  2.2643e-01,
         -1.5486e+00, -2.4911e+00,  1.3089e-01,  1.2135e+00, -2.6380e+00],
        [-6.0109e-01, -1.4022e+00, -1.1291e+00, -3.9274e-01,  8.9849e-02,
         -9.0763e-01,  4.6464e-01, -5.9253e-01,  8.2619e-01,  2.4516e+00],
        [ 1.0161e+00, -1.0637e-01,  1.4930e+00,  8.0728e-01,  2.4033e-01,
         -5.3844e-01,  1.6548e+00,  8.3420e-03,  6.2744e-01, -1.0980e+00],
        [ 4.2749e-01, -6.8016e-01, -2.9928e-01,  1.0795e+00,  2.6041e-01,
          6.7689e-01,  1.3593e-01, -7.1369e-02,  2.7712e+00, -1.3757e-01]])
torch.Size([6, 10])


In [7]:
# 4. Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
c = torch.randint(20, size = (10, ))
c = c.int()
print(c)
print(c.type())

tensor([ 5,  4,  6,  7, 12, 15,  7, 10, 10,  9], dtype=torch.int32)
torch.IntTensor


In [8]:
# 5. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

d = c * b
print(d)
print(d.shape)

tensor([[-9.5371e+00,  1.5768e+00,  5.9723e+00,  4.9128e+00,  7.7302e+00,
         -3.9610e+00,  8.7747e+00,  1.6054e+01,  1.9917e+00,  1.7048e+01],
        [ 5.5299e+00, -5.2486e-01,  5.7769e+00, -8.9475e-02,  2.3952e+01,
          1.4309e+01, -3.0206e+00, -5.1356e+00,  6.3469e+00,  4.2499e+00],
        [-3.0127e+00,  3.3083e+00, -1.3880e-02,  4.4167e+00,  2.7172e+00,
         -2.3229e+01, -1.7438e+01,  1.3089e+00,  1.2135e+01, -2.3742e+01],
        [-3.0055e+00, -5.6090e+00, -6.7748e+00, -2.7492e+00,  1.0782e+00,
         -1.3614e+01,  3.2525e+00, -5.9253e+00,  8.2619e+00,  2.2064e+01],
        [ 5.0803e+00, -4.2550e-01,  8.9581e+00,  5.6509e+00,  2.8839e+00,
         -8.0765e+00,  1.1584e+01,  8.3420e-02,  6.2744e+00, -9.8818e+00],
        [ 2.1375e+00, -2.7206e+00, -1.7957e+00,  7.5565e+00,  3.1250e+00,
          1.0153e+01,  9.5150e-01, -7.1369e-01,  2.7712e+01, -1.2381e+00]])
torch.Size([6, 10])


In [9]:
# 6. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)
y = x**3 + z -75*t
y.backward([x, z, t])
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [10]:
# 7. Создайте единичный тензор размера 5x6

f = torch.ones(5, 6)
print(f)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [11]:
# Переведите его в формат numpy

f.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)